### ISSUE TITLE
[W3-pipelines-project] Jacobo Martín-Cubas Núñez

### ISSUE THREAD

**Issue by marcunu** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#1]
https://github.com/marcunu/API-Scrap.git

**Comment by breogann** [comment]
Hola Jacobo! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: runners worldwide
- Enriquecido con: API strava + scrappeo

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: perfecto! no se te ha colado ningún archivo temporal y te has acordado de añadir el `.env`
    - Los archivos de código irían en la carpeta de `src`  . Entiendo que los tienes fuera porque son tus ejeutables, ¿no? Siendo así, los ejecutables suelen ser un arhcivo que se llama [app.py](http://app.py) o [main.py](http://main.py). Luego, si ese archivo necesita otro, llama a funciones de otro sitio. La cosa del ejecutable es que, más que tener todas las líneas que tenías en jupyter, tenga funciones a las que llamas.
- El **[README.md](http://readme.md) ✍🏻**: está muy bien. Has explicado el objetivo del proyecto, puesto las librerías que utilizas y el origen de la información.

- El ejecutable ⚡️: lo que te decía, lo único que te falta es que ese código esté guardado en funciones.

- Respecto al código 👩‍💻:
    - En el **src**:
        - Llama y organiza los archivos según su contenido. Si el archivo es de limpieza, no incluyas la función de ciudad (lon_lat). Organízlos según contenido.
        - Genial las docstrings
        - Las funciones de ciudad y comunidad y país son exactamente iguales; excepto por una cosa: por lo que se puede parametrizar.
    - En los **jupyters**:
        - API information.ipynb:
            - Limita el oputput 🙏
            - Recuerda no dejar los errores puestos
            - Muy bien el diccionario para guardar la información
            - El procesamiento de los datos/código lo veo bastante bien
        - Visualization.ipynb:
            - El pairplot déjalo sóllo si te aporta información; si lo utilizas como guía sobre la que apoyarte, genial, pero luego recuerda borrarlo si no aporta.
            - La visualización en general está bastante bien
            - Algo que puedes hacer es plotear una gráfica de un dataset y utlizar la axvline con la media de otro dataset para poder comparar y cruzar datos de datasets diferentes en la misma visualización

En resumen: 

- Los ejecutables con funciones modularizadas. Ya las tienes en otros archivos, es cuestión de importarlas y llamarlas
- Los archivos de código tienen que estar organizados de forma significativa: tiene que haber alineación con nombres/contenidos.
- La parte del enriquecimiento: muy top, has utilizado tres fuentes diferentes de datos.
- El código lo veo bien también

Has utilizado un dataset, una API, scrapping y  limpiado sacado insights con la visualización. 

A tope Jacobo! 💪
Pd.: tienes los jupyters duplicados? (en la carpeta de jupyter y en la root)

**Comment by marcunu** [comment]
Muchas gracias por la corrección Fer.
En cuanto a los duplicados fue porque en un principio tenia todo en las misma carpeta y como eran los jupyter que utilice para generar los ejecutables los meti en una carpeta nueva, pero se me paso desenlazarlos de la carpeta principal.

Un saludo,
Jacobo.

De: Fernando ***@***.***>
Enviado: martes, 20 de abril de 2021 12:48
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project] [W3-pipelines-project] Jacobo Martín-Cubas Núñez (#1)


Hola Jacobo! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal.

El proyecto tenía dos objetivos: enriquecer datos & hacer un pipeline.

  *   Para el primero: utilizar una API o web scrapping para relacionar los datos.
  *   Para el segundo: que haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

ruta > df_descargado > df_limpio

Has utilizado:

  *   Dataset original: runners worldwide
  *   Enriquecido con: API strava + scrappeo
  *   Respecto a la organización del repositorio 📚
     *   El .gitignore: perfecto! no se te ha colado ningún archivo temporal y te has acordado de añadir el .env
     *   Los archivos de código irían en la carpeta de src . Entiendo que los tienes fuera porque son tus ejeutables, ¿no? Siendo así, los ejecutables suelen ser un arhcivo que se llama app.py<http://app.py> o main.py<http://main.py>. Luego, si ese archivo necesita otro, llama a funciones de otro sitio. La cosa del ejecutable es que, más que tener todas las líneas que tenías en jupyter, tenga funciones a las que llamas.
  *   El README.md<http://readme.md> ✍🏻: está muy bien. Has explicado el objetivo del proyecto, puesto las librerías que utilizas y el origen de la información.
  *   El ejecutable ⚡️: lo que te decía, lo único que te falta es que ese código esté guardado en funciones.
  *   Respecto al código 👩‍💻:
     *   En el src:
        *   Llama y organiza los archivos según su contenido. Si el archivo es de limpieza, no incluyas la función de ciudad (lon_lat). Organízlos según contenido.
        *   Genial las docstrings
        *   Las funciones de ciudad y comunidad y país son exactamente iguales; excepto por una cosa: por lo que se puede parametrizar.
     *   En los jupyters:
        *   API information.ipynb:
           *   Limita el oputput 🙏
           *   Recuerda no dejar los errores puestos
           *   Muy bien el diccionario para guardar la información
           *   El procesamiento de los datos/código lo veo bastante bien
        *   Visualization.ipynb:
           *   El pairplot déjalo sóllo si te aporta información; si lo utilizas como guía sobre la que apoyarte, genial, pero luego recuerda borrarlo si no aporta.
           *   La visualización en general está bastante bien
           *   Algo que puedes hacer es plotear una gráfica de un dataset y utlizar la axvline con la media de otro dataset para poder comparar y cruzar datos de datasets diferentes en la misma visualización

En resumen:

  *   Los ejecutables con funciones modularizadas. Ya las tienes en otros archivos, es cuestión de importarlas y llamarlas
  *   Los archivos de código tienen que estar organizados de forma significativa: tiene que haber alineación con nombres/contenidos.
  *   La parte del enriquecimiento: muy top, has utilizado tres fuentes diferentes de datos.
  *   El código lo veo bien también

Has utilizado un dataset, una API, scrapping y limpiado sacado insights con la visualización.

A tope Jacobo! 💪
Pd.: tienes los jupyters duplicados? (en la carpeta de jupyter y en la root)
