### ISSUE TITLE
[W3-pipelines-project] Bertrán Gil 

### ISSUE THREAD

**Issue by Bertrangsf** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#10]
https://github.com/Bertrangsf/2.-GOLD-pipeline.git

**Comment by AnaAGG** [comment]
# 💲 Proyecto Pipelines 💲 

Hola hola Bertrán 🙋‍♀️, aquí estoy de nuevo con la corrección del proyecto de pipelines!

## Readme

Enhorabuena Bertrán, has hecho un trabajo buenísimo en este readme! Estoy muy contenta, has creado un readme muy claro, con todas las ideas de tu proyecto, muy conciso y todo suuper organizado. Además, has añadido todas las recomendaciones que te dimos la semana pasada, muy bien!!! 🔝
Te dejo por aquí algunos comentarios sobre algunas cosas que se podrían pulir, pero son detallines (por ponerme un poco tiquismiquis 😉):  

- Cuando pones las librerias que has usado durante el proyecto, sería top que pudieras añadir un link que te llevara a la documentación oficial de cada una de las librerias. 

- Recuerda, no hace falta que pongas `import pandas`, con que pongas `pandas` es suficiente. 

## Estructura del repositorio
En cuanto a la organización esta todo super bien. No has dejado los csv de los datos pero si los links para que la gente se los pueda descargar. Super bien esto cuando los datos vienen de kaggle. 
- Solo a modo de detalle, tienes todos los jupyter en la carpeta análisis lo cual esta bien, pero te dejaste uno fuera. Esto es un detalle no es importante! 

- Si numeras los jupyter para saber en que orden van, estaría perfectísimo!

- Suuuper bien todas las funciones con sus docstrings 🚀


## Sintaxis de código

Vamos con las cosas de código:

- Cuando haces la función `month`. Esta función esta perfecta, es pequeña con un objetivo específico y que además es generalizable. Pero si te fijas no te hace falta el bucle `for`. La puedes crear igual ya que luego usarás un `apply` y con esto lo que harás es aplicar esta función a cada elemento del la columna que quieras. 
    ```python
    def month(date):
        for x in date:
            months = int(date[-2:])
            return calendar.month_name[(months)] 
    ```
    Lo mismo para todas estas funciones que tienes creadas para extraer un valor determinado de la fecha.  

- Muy buen trabajo en la función `converttopdf`. No solo has creado una función que te hace el scrapeo, además has llamado a otra función dentro de esta

## ToDo

- Te faltan algunos docstrings, dale duro ahí! Que quede todo super bien

- En el proyecto has sacado información sobre el precio del oro de dos fuentes de datos lo que esta genial, pero en la visualización me ha faltado un poco de *story telling* que nos contarás algo sobre los datos, como se relacionan o que diferencias encontrabas. Un poco de interpretación de las gráficas.  

- Me ha faltado el .py ejecutable, pero por el resto todo muy bien Bertrán. 

Bueno Bertrán menudo cambio entre el primer y el segundo proyecto. Enhorabuena, hiciste muy buen trabajo 💪. En este lab has aprendido a seleccionar un buen dataset, lo has enriquecido con scrapping. Has cubierto todos las directrices que os pediamos para este proyecto 😀. 

![image](https://user-images.githubusercontent.com/75084991/114836334-d2c8cc80-9dd2-11eb-917d-e8d53448d8a4.png)
