### ISSUE TITLE
[W3-pipelines-project]Carmen R 

### ISSUE THREAD

**Issue by Carmen-r** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#11]
https://github.com/Carmen-r/W3-pipelines-project.git

Soy consciente de que no está completo, ayer decidí cambiar de tema porque me daba muchos problemas la API y el tema que escogí no me gustaba mucho.

**Comment by breogann** [comment]
Hola Carmen! 🙋🏻‍♂️

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: Netflix shows (kaggle)
- Enriquecido con: web scrapping IMDB
- Has relacionado los datos con: rating

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: genial, no se te ha colado ningún archivo temporal.
    - La carpeta de `midatasetlimpio` : esos csv's irían en la carpeta de input o la de data.
    - Por lo demás, la organización está clara: tienes una carpeta de src y tienes los jupyters numerados.

- El **[README.md](http://readme.md) ✍🏻**: necesitas un README. No utilicéis el nuestro! Tienes que hacer uno donde expliques todo el proceso: extracción, transformation, loading, etc.  Y es importante que indiques de dónde han salido los datos y de dónde coges los nuevos.

- El ejecutable ⚡️: tenéis la función de descarga. Podéis o no utilizarla en función del origen del dataset (si es de Kaggle o no). Puedes utilizar las funciones que tienes en tu archivo de limpieza y simplemente importar el csv y llamarlas.

- Respecto al código 👩‍💻:
    - En el **src**:
        - No tienes las dosctrings! Son importantes, es la documentación propia de las funciones. Deberían tener: una descripción de lo que hace y qué argumentos reciben (y de qué tipo) y qué devuelven (y en qué tipo).
        - En la función de regex:

            ```python
            def date(patron, string):
                import re
                try:
                    return re.search(patron, string).group().lower()
                except:
                    return f"Error"
            ```

            el import tiene que ir fuera! 

            Search te devuelve un objeto, ¿te funciona tal y como lo tienes?

        - Por lo demás, tienes pocas funciones; puedes incluir las de scrapping, por ejemplo. Todo el código que tengas en jupyter probablemente se pueda modularizar (meter en funciones).
    - En los **jupyters**:
        - 01. Exploración y limpieza .ipynb:
            - ¿Has ejecutado la función de descarga del dataset pero no la has importado?
            - Las lambdas con el apply están perfectas.
        - 02. Scraping Filmaffinity.ipynb:
            - Gracias por haber limitado el output 🙏
            - Genial también la comprehension list
        - 03. Scrapping IMDB.ipynb:
            - Importas las funciones desde limpieza.py. Luego recuerda borrarlas del jupyter.
        - 04. Concat FilmAffinity_Netflix.ipynb:
            - ¿Sólo coges directores que "interesan"? Es porque están más accesibles los datos? 👀
        - 05. Visualización.ipynb:
            - Aquí:

                ```python
                df3['Title'] = df3['Title'].replace(['Joker .'],'Joker')
                df3['Title'] = df3['Title'].replace(['Vengadores: Infinity War .'],'Avengers: Infinity War')
                df3['Title'] = df3['Title'].replace(['Thor: Ragnarok .'],'Thor: Ragnarok')
                df3['Title'] = df3['Title'].replace(['El juicio de los 7 de Chicago .'],'The Trial of the Chicago 7')
                df3['Title'] = df3['Title'].replace(['Black Panther .'],'Black Panther')
                ```

                puedes create un diccionario para sustituir las keys por las values y entonces aplicar la función a la columna Title.

            - Respecto a la visualización, seguro que puedes sacar algún otro gráfico más!
            - Súuper top que hayas metido la visualización en la función. Puedes hacer lo mismo con el scrapping. Y estas funciones las puedes meter en un ejecutable. También le puedes añadir una línea para guardar la función en tu carpeta de output.

En resumen: te falta el ejecutable, pero tal y como tienes el código es súper fácil de conseguir. Has enriquecido un dataset haciendo scrapping y tienes una buena organización del proyecto. Tu código, por lo general, está bastante bien: está "recogido" y es el necesario para hacer lo que tienes que hacer. Sólo te queda hacer más modularización y el ejecutable.

Está muy bien el proyecto Carmen! 💪
