### ISSUE TITLE
[W3-pipelines-project] Edu Martínez

### ISSUE THREAD

**Issue by EduMartinezGarrido** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#12]
https://github.com/EduMartinezGarrido/Triatlon_Api

**Comment by AnaAGG** [comment]
# 🏁 Proyecto Pipelines 🏁

Hola hola Edu 🙋‍♀️, aquí estoy de nuevo con la corrección del proyecto de pipelines!

## Readme

En el readme me han faltado algunas cositas:
- Cuando mencionas las librerías usadas en el proyecto te dejo tres comentarios:
    - No hace falta que pongas `import re`, pon solo `re`. 

    - No hace falta que pongas en la lista las funciones que importas desde tu propios `.py`. No son librerías. 

    - Si pones los links a la documentación oficial de cada librería estaría suuper bien. 

- Me ha faltado un poco de contexto en el proyecto. Explicas bien lo que haces y con que lo haces, pero no para qué. ¿Por qué estos datos, qué es lo que estas buscando?


## Estructura del repositorio

- Se te ha pasado algún fichero que debería ir en el `.gitignore` como el `.ipynb_chechpoints`, el `.DS_Strore`, `__pycache__` y lo que es más importante ⚠⚠ ‼ **el token de la API** ‼ ⚠⚠

- Todas las importaciones de librerías mejor al inicio del jupyter


## Sintaxis de código

- Cuando haces la segunda llamada a la API, la estructura de código que tienes es: 
    - Crearte una lista de urls.
    - Hacer una request a cada una de las url.
    - Extraer ciertos datos de cada uno de los atletas y almacenarlos en listas.
    - Crear diferentes dataframes, uno para cada lista.
    - Hacer un join de todas las tablas. 
    
    Si te fijas tienes mucho código repetido. Cuando pasa esto lo mejor es **atomizar el código**. ¿Cómo lo podrías hacer?
    - Puedes crearte una lista con los id de los deportistas y luego hacer las `requests` con un `for` para cada uno de los atletas.
    -  Luego te creas un diccionario donde los *values* serán la info que quieres de cada atleta
    - Por último, haces un dataframe de ese diccionario. 

- Me ha faltado alguna función más. Por ejemplo, cuando importar el excel y lo unes con los datos de la API, todo ese proceso de limpieza lo podrías meter en un función. 

- En el jupyter de limpieza, empiezas limpiando datos, esto lo ideal es que lo hicieras en el `.py`. Aquí de nuevo si te fijas vuelves a tener unas estructuras de código repetidas. Puedes haces esto y se te aplicará a todos los `NaN` del dataframe
    ```python
    df = df_total.fillna("Unknown")
    ```
- Vamos a por las gráficas! Suuper bien Edu has hecho un montón de gráficas explorando al máximo tus datos. Te dejo por aquí algunos comentarios por si te aportan valor:
    - En la primera gráfica, donde usas el `input`, esta suuuper bien, puedes crear una función con ese código y ya sería perfecto. Muy bien esa programación defensiva, pero puedes usar un `try`, `except` en este caso. 

    - Hay algunas gráficas que repites varias veces, como los histogramas o los scatterplots. El código esta perfecto, pero podrías crear una función para hacer estas gráficas y no tener que repetir el código todo el rato. 

    - Los `scatterplots` que no te salían es por dos motivos:
        - Las columnas `height` y `weight` son de tipo `object`. Lo primero que tendrías que hacer es convertirlas a número. Recuerda el método `to_numeric` de pandas. 

        - Al inicio del jupyter quitas los NaN por "unknown", esto también te dará error en el plot. Te dejo por aquí una posibilidad para ese plot
            ```python
            df.dropna(subset=['Height', 'Weight'])
            df["Height"] = pd.to_numeric(df["Height"])
            df["Weight"] = pd.to_numeric(df["Weight"])
            sns.scatterplot(x="Height", y="Weight",data=df)
            ```
## ToDo

- Cuando veas que tienes un `print` muy muy largo intenta limitar el print. Es por limpieza del jupyter, que el que vaya a leer tu repo no tenga que hacer un scroll infinito y porque se puede saltar alguna línea de código haciendo el scroll. 

- En la visualización eché de menos que explicaras cada gráfica un poquito, meter un poco de *story telling*. 

- Me ha faltado el ejecutable, un archivo que al ejecutarlo en la terminal me devuelva todo descargado y limpio. 

En general Edu, en este proyecto tenias que descargar un dataset y enriquecerlo con datos de APIs o *webscrapping*, para después combinar todos los resultados y sacar conclusiones. Has conseguido todos los objetivos, muy buen trabajo Edu. 

![image](https://user-images.githubusercontent.com/75084991/115104756-d4250100-9f5a-11eb-866c-efbbd86556f4.png)
