### ISSUE TITLE
[W3-pipelines-project] Pablo Fernández Cañete

### ISSUE THREAD

**Issue by pfernancanete** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#13]
No he conseguido relacionar los monumentos con los pisos. Seguiré trabajando en ello.

**Comment by pfernancanete** [comment]
https://github.com/pfernancanete/-W3-pipelines-project-

**Comment by AnaAGG** [comment]
# 🕍🕌 Proyecto Pipelines 🛕🕌

Hola hola Pablo! Vamos con las correcciones del proyecto de las Pipelines 

## Readme
En general el readme esta bastante bien, claro, conciso y muy ordenado. Te dejo por aquí unos comentarios sobre algunos detalles para el futuro: 

- En el apartado de `Introduction` planteas una pregunta lo que esta genial. Quedaría perfecto si le metes un poco de contexto, un poco de *story telling* para poner en contexto al lector. 

- La gráfica que pones esta muy bien, pero se ve un poco regulinchi con el fondo negro y las letras en negro... Pero vamos esto es un detalle.

- Cuando pones las librerías, estaría super que pusieras los links a las páginas de la documentación oficial. Si tienes alguna duda sobre como hacer esto coméntamelo y lo miramos 😉


## Estructura del repositorio

- El título del proyecto no hace falta que sea el que os damos nosotros. Puedes cambiarlo y ponerle algo que describa más tu proyecto. 

- Cuando mencionas el dataset de kaggle sería la leche si pusieras un link a la página donde se pueden descargar el archivo. 

- No se ha colado el fichero de kaggle por ahí, suuuper bien esto Pablo. Importante meterlo en el `.gitignore`

- Has documentado las funciones lo cual esta bien. Pero en python hay un convenio para hacerlo. Te dejo por aquí un ejemplo:
    ```python
    def clean_listing(stay):
        '''
        Que hace la función. Función de limpieza de un dataset para eliminar columnas, nulos y duplicados
        Que recibe. Recibe:
                stay(dataframe): dataframe con el que estemos trabajando
        Que devuelve. Devuelve:
                devuelve el mismo dataset limpio. 
        '''
        stay = stay.drop(['minimum_nights', 'last_review', 'reviews_per_month', 'calculated_host_listings_count', 'availability_365'], axis = 1 )

        stay.isnull().sum().sort_values(ascending=False)
            
        stay.dropna()
            
        stay.drop_duplicates()
    ```

## Sintaxis de código

- La primera función que tienes creado `clean_listing` no tiene `return`, por lo tanto te devolverá `None` cuando la ejecutes. 👀 con esto cosas!

- Super top 🔝 que te hayas lanzado con webscrapping. Sobre el jupyter te dejo por aquí algunos comentarios: 
    - Igual que en el jupyter de `clean_listing` hubiera estado bien que crearás funciones para el scrapping. Por ejemplo, que le pases la url y te exporte un csv con el dataset limpio. En esta función podrías meter todos los pasitos pequeños que has ido haciendo en el este jupyter. 

    - Cuando creas el dataframe del diccionario usando el método `from_dict` puedes aprovechar los parámetros propios de este método para atomizar líneas de código:

    ```python
    latlon = pd.DataFrame.from_dict(geoloc, orient='index', columns = ["Latitude", "Longitude])
    latlon.reset_index()
    latlon
    ```

## ToDo

- Me ha faltado el archivo ejecutable `.py`

- Crear la vinculación entre todos los datos que obtuviste para este proyecto. 

- La visualización esta un poco más flojita, queda meterle un poco de historia, explicar un poco más los resultados que te salieron. 

![image](https://user-images.githubusercontent.com/75084991/114983582-15e97500-9e91-11eb-9751-0f1b63ec80a2.png)
