### ISSUE TITLE
[W3-pipelines-project] Pablo FR

### ISSUE THREAD

**Issue by fromeropablo** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#14]
https://github.com/fromeropablo/Project-week-03

**Comment by breogann** [comment]
Hola Pablo! 🇮🇨🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: NBA players
- Enriquecido con: scrapping/API

- Respecto a la **organización del repositorio 📚**
    - El .gitignore:

        ![image](https://user-images.githubusercontent.com/54676992/115257230-2a976880-a130-11eb-9049-f558d7ac4b21.png)

        de hecho, tienes una carpeta de temporal que se te ha colado: **pycache.** 

    - Ponle un título significativo al proyecto. Recuerda que es vuestro portfolio.
    - Por lo demás, la organización está clara: tienes una carpeta de src y tienes los jupyters numerados y organizados en un carpeta de notebooks; así está perfect.

- El **[README.md](http://readme.md) ✍🏻**: está muy bien. Has explicado el objetivo del proyecto, enlazado las librerías y también el dataset que utilizas. Puedes poner también la página que utilizas para escrapear.

- El ejecutable ⚡️: ya tienes archivos de scrapping, es cuestión de simplemente importar el df y llamar a las funciones.
- Respecto al código 👩‍💻:
    - En el **src**:
        - Genial por usar el map:

            ```python
            data.columns = map(str.upper, data.columns)
            ```

        - La función de cleaning_data no recibe ningún dataframe, entiendo que tu df se llama así, ¿no?
        - Aquí:

            ```python
            def scrapping():
                url = "https://www.acb.com/club/estadisticas/id/"
                headers = res.findAll("thead")[0].findAll("tr")[1].text.replace("\n", ",").split(",")
                headers = ['NADA','PLAYER_NAME', 'GP','MIN/G','5i','PPG','3FGM','3FGA','3FG%','2FGM','2FGA','2FG%','FTM','FTA','FT%',
                       'DREB','OREB','TREB','ASIST','ST','TO','BLK','RBLK','DUNKS','PF','RPF','+/-','VAL']

                stats_list = []
                for year in range(2000, 2021):
                    for team in range(1,20):
                        html = requests.get(url+"{}".format(team)+"/temporada_id/"+"{}".format(year))
                        res = BeautifulSoup(html.content,"html.parser")
                        table = res.find("tbody")
                        rows = table.findAll("tr")
                        for r in rows:
                            elements = r.findAll("td")
                            jugador = [e.getText().strip() for e in elements]
                            stats_list.append(jugador)  

                        return stats_list
            ```

            entiendo que has cogido las funciones de jupyter y las has pasado a este archivo, pero luego no las has vuelto a utilizar en jupyter. El return está dentro de un bucle, así que sólo haría la primera iteración. Tendría que estar sin indentación. Cuando tengas un hueco, vuelve y cámbialo! 

        - Lo mismo con esto:

            ```python
            return plt.show
            else:
            return election
            ```

            este código no lo puedes dejar así con errores de indentación.

        - En cualquier caso, tienes el código en funciones, y con poco que modifiques puedes hacer un ejecutable: si tienes las funciones definidas, sólo tendrías que llamarlas.
    - En los **jupyters**:
        - Como ya te dijimos en la presentación, te falta la parte de visualización.
        - También, una vez modularizadas las funciones, tienes que sustituir el código de las celdas para poner las funciones importadas.
    - También te falta el ejecutable

En resumen: te falta el ejecutable, pero tal y como tienes el código es súper fácil de conseguir (cuestión de llamar lo que ya tienes definido). Has enriquecido un dataset haciendo scrapping y tienes una buena organización del proyecto. Y utilizar la API de la página que has escrapeado es de genio. 

Sé que te has peleado con el código, con el scrapping y que te lo has currado. Puliendo unos pocos detalles eso se puede hacer ver en el repo.

Ánimo Pablooooo! 💪
