### ISSUE TITLE
[W3-pipelines-project] Luis Sánchez de León 

### ISSUE THREAD

**Issue by lsdl13** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#15]
No pude ni si quiera profundizar en el desarrollo de este proyecto (no me funcionaron un par de llamadas a Apis que encontré por ahí) como bien comenté hace un par de semanas a la organización del curso. Lo iré completando en los próximos días.

**Comment by lsdl13** [comment]
https://github.com/lsdl13/Proyecto2-pipelines.git

**Comment by breogann** [comment]
Hola Luis! 🙋🏻‍♂️

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: MVP's
- Enriquecido con: web scrapping [https://en.wikipedia.org/wiki/EuroLeague_MVP](https://en.wikipedia.org/wiki/EuroLeague_MVP)'

Como tú mismo dices, el proyecto está incompleto, Luis. 

- Respecto a la **organización del repositorio 📚**
    - Cuando lo tengas, necesitarás una carpeta `src`donde guardes el código con los archivos de funciones.
    - Los archivos de funciones tendrán que tener nombres significativos: scrapping.py, cleaning_dataset.py, etc. Nunca llames al archivo de funciones ``funciones.py`
    - El .gitignore:
        - Has utilizado la plantilla de github pero se te ha olvidado añadir otras cosas. Se te ha colado por ejemplo el archivo .DS_Store dentro de la carpeta input. Echa un ojo a los gitignore de los labs, que ahí tenemos tres o cuatro líneas para ignorar este tipo de archivos de forma recursiva.

- El **[README.md](http://readme.md) ✍🏻**: Está muy completo el readme. Asegúrate de quitar el enlace del final si el repositorio lo borraste. Lo que te falta y es muy importante es un enlace al dataset o la fuente de donde la sacaste.

- El ejecutable ⚡️: tenéis la función de descarga. Podéis o no utilizarla en función del origen del dataset (si es de Kaggle o no). Cuando tengas las funciones, mínimo, mínimo tendrás que pasar las funciones de limpieza.

- Respecto al código 👩‍💻:
    - Las rutas siempre tienen que ser relativas, nunca absolutas.

Este proyecto es importante porque sigue el ETL, que es Extract, transform & load. Es un trabajo esencial para un data analyst. Mañana hay otro proyecto, así que no tendrás mucho tiempo para mejorar este (quizá durante algún fin de semana). Intenta hacerte una lista de pasos pequeños que tienes que seguir para ir mejorándolo poco a poco:

- Ej.: dar estructura al proyecto: crear carpeta src, crear un archivo de limpieza
- Limpiar nulos etc del dataset original
- Limpiar la parte que me interesa del dataset
- Encontrar el div, class, etc que necesito para el scrapping. Sólo encontrarlo.
- Hacer código para escrappear toda la tabla

 etc. 

Cualquier cosa nos dices, y cuando tengas actualizaciones, avísanos y le echamos un ojo!
