### ISSUE TITLE
[W3-pipelines-project]Alberto Pérez

### ISSUE THREAD

**Issue by asiokfd** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#16]
https://github.com/asiokfd/Proyecto2

**Comment by AnaAGG** [comment]
# 💲 Proyecto Pipelines 💲 

Hola hola Alberto 🙋‍♀️, aquí estoy de nuevo con la corrección del proyecto de pipelines!

## Readme
Vamos con el readme, ya me comentaste que te queda pulirlo, te dejo por aquí algunos comentarios por si te aportan valor para el futuro:

- Cuando especificas las librerías que usaste estaría muy bien que pusieras los links a las páginas oficiales de la documentación. 

- Especifica de donde te has descargado los datos y haz una pequeña descripción de ellos para poner al lector un poco en contexto. Que sepa que se va a encontrar cuando vaya a mirar el proyecto. 


## Estructura del repositorio

En cuanto a la estructura, muy bien que tengas las carpetas de imágenes y data. Muy bien documentado cada pasito que das 🔝 A modo de detalle:
- Estaría bien que metieras todos los ficheros `.py` en una carpeta que se llame `scr`. Esto es más convenio que otra cosa, pero así la gente que vea tu repo sabrá que ahí están los archivos `.py` con los ejecutables y las funciones. 

- Tienes varios archivos `.py`, en el readme explicas un poco el orden, pero si ya pones números en cada fichero para saber el orden estaría perfecto. 

- Super, tienes todos los ficheros "especiales" en el `.gitignore` no se te ha pasado nada. 

- Te animo a que en los jupyter uses las celdas de tipo markdown cuando añades comentarios al jupyter. Te darán mucho más juego, poner palabras en negrita, en cursiva, crear índices... 

- ❗ Acuerdate, los import siempre al incio del jupyter ❗

- Tienes algunos `import` dentro de las funciones, lo ideal es que estén fuera. Si las sacabas te daba error?

## Sintaxis de código

Vamos con el código:

- En el ejecutable `for_investemnt.py`, cuando defines la función `aceptarcookies` no recibe ningún parámetro, pero cuando la llamas en en `Proyecto2.py`) le pasas un parámetro (`url_previa`). Esto te dará error ya que le estas pasando un parámetro que no estaba definido. ¿Cómo lo podrías hacer?
    ```python
    def aceptar_cookies(url):
        from selenium import webdriver # ⚠ intenta ponerlo fuera de la función  

        """ Esta función recibe una url de investing.com y acepta las cookies"""
        html = driver.get(url) #version del request de selenium, abrir página
        url= driver.find_element_by_id("onetrust-accept-btn-handler").click() #y empezamos a navegar, en este caso aceptamos cookies
        return url
    ``` 
    🟠 Lo mismo te pasa para el resto de las funciones que tienes definidas para selenium. Si las defines sin parámetros, cuando las llamas no le puedes pasar ninguno. 

- La columna `Unnamed: 0` es la columna es la del índice y se te crea cuando haces la exportación del dataframe a csv. Hay dos formas en que puedes evitar tener que quitarla: 
    - Cuando estas exportando el *dataframe* :
        ```python
        df.to_csv('file.csv', index=False)
        ```
    - Cuando cargas el csv:
        ```python
        pd.read_csv('file.csv', index_col=[0])
        ```
- Para tu objetivo final en pandas existe el método [`date_range`](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.date_range.html) que te permite seleccionar un rango de fechas en función de una fecha dada. Te dejo por aquí unas líneas de código por si te aportan valor. 
    ```python
    i = pd.date_range('2021-04-06', periods=4) # buscará las 4 siguientes fechas a la fecha dada

    subset = historico[historico.Fecha.isin(i)] #tendremos un dataset con aquellas filas que correspondan a las fechas que estabamos buscando
    ```
    Después de esto ya podrás calcular la media, máximos o mínimos para cada una de las columnas que quieras y compararlos!

## ToDo

- Venga, dale al jupyter de la visualización, me he quedado con ganas de cerrar la historia, ver todos los datos juntos y ver grafiquitas. Tienes algunas gráficas sacadas, pero sin el código. Y sobre todo cuando hagas las gráficas explícalas 😉. 

- Al readme le falta un pelín, pero no esta mal!

- El `.py` lo tienes casi casi, te faltaban algunas cosas, como lo de las funciones que las defines sin parámetros y luego se los pasas.  Si tienes dudas con esto, pregúntanos 😉

- Intenta esto que te comentaba sobre el `data_range`.

- Sobre la estructura del repo, hay un poco de jaleo en algunos ficheros, sobre todo en el orden que hay que seguir, y que tienes funciones para el scrapeo separadas en distintos ficheros.

Si te quedas con alguna duda ya sabes donde estamos!!! 

Bueno Alberto, en este proyecto te han quedado algunas cosas pendientes, pero lo que hiciste esta suuper bien. Te lanzaste con `selenium`, una herramienta que no os han explicado y que no es fácil! Enhorabuena por esa parte 👏👏. Te ha faltado la parte de visualización, pero estoy segura que lo acabaras haciendo 💪. 

![image](https://user-images.githubusercontent.com/75084991/115233462-38d98a80-a118-11eb-8100-6d214d128bb4.png)
