### ISSUE TITLE
[W3-pipelines-project] Cristina Callejo

### ISSUE THREAD

**Issue by CristinaCallejo** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#17]
El segundo .py he tenido que separarlo del retso, no me dejaba usar format strings desde el code. 
Seguiré actualizando para acabar con las visuals, jo, le he puesto _mucha_ chicha para que rule el .py : 
[Pipelines]((https://github.com/CristinaCallejo/Pipelines)

**Comment by breogann** [comment]
Hola Cris! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: está genial. Has cogido la plantilla de gitub y te has quedado con lo que te hacía falta 👌
    - Para la numeración del os jupyter: tienes un segundo pero no un primero; y el resto no tienen numeración. No drama, pero para que tenga más consistencia.
    - Por la parte de separar los jupyter y src, muy bien.

- El **[README.md](http://readme.md) ✍🏻**: ¿qué te voy a decir? 🔪🔪

- El ejecutable ⚡️:
- Respecto al código 👩‍💻:
    - En el **src**:
        - He visto que pones varias veces:

            ```python
            if True:
            ```

            esto siempre se va a ejecutar. Siempre va a ser True. Es como que ese statement se evalúa a sí mismo, entonces siempre va a hacer lo que tiene debajo. 

        - Para las funciones: las has parametrizado, pero las has parametrizado para luego llamarlas con variables asignadas:

            ```python
            datas = import_csv_and_clean_and_lowercase_and_export(
                dir_incoming,
                dir_outgoing,
                st,
                dropping_lst,
                renamed_lst,
                lowering_lst
            )
            ```

            puedes directamente llamarlas:

            ```python
            datas = import_csv_and_clean_and_lowercase_and_export(
            "./data_inputs/", "./data_processed/", "regional_sp_2021_03_05.csv"
            ```

            etc. Pero esto es más preferencia personal. 

            En cualquier caso está muy bien porque has modularizado las funciones y luego las llamas, que es algo que no ha hecho mucha gente. 

        - Este apply con lamba:

            ```python
            dataf = dataf.apply(lambda x: x.str.lower() if x.name in lowering_lst else x)
            ```

            está genial. 

        - Esta función:

            ```python
            def export_df_to_csv(dataf,st):
                dataf.to_csv(dir_+ "v2" + st[2:], index = False)
                if True:
                    print('Step 1 of !: export as new .csv = SUCCESSFULL')
                    print("Ended process: exported ", st, "to: v2" + st[2:], "in: ", dir_)    
                else:
                    print('NOT succesfull, check format')
                return dataf
            ```

            la puedes refactorizar:

            ```python
            def export_df_to_csv(dataf,st):
            	try:
                return dataf.to_csv(dir_+ "v2" + st[2:], index = False)
            	except:
            		print('NOT succesfull, check format')
            ```

        - Lo que tienes comentado, está comentado a forma de borrador? Si es así, bórralos!
        - En statistical_analysis.py no tienes estadística 👀
    - En los **jupyters**:
        - Están mejorables. Importas las funciones pero también las tienes definidas en algunos de los jupyters.
        - Tienes jupyters prácticamente vacíos

En resumen: tienes el ejecutable, pero si los jupyters no los utilizas, bórralos. Falta un poco de organización y el READMEEE. El código en general está bien. Quizá alguna función que hace muchas cosas se puede separar para que lo haga otra función más pequeña. 

Ánimo Criiis! 💪
