### ISSUE TITLE
[W3-pipelines-project] Unai Arteaga 

### ISSUE THREAD

**Issue by Unaiat** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#19]
https://github.com/Unaiat/Basketball---Pipeline-project

**Comment by breogann** [comment]
Hola Unai! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: NBA players
- Enriquecido con: Balldontlie API
- Otros 2 csv's

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no tienes, y tienes archivos temporales repartidos por varias carpetas. Tienes que:
        - crear el .gitignore
        - borrar del caché los archivos con

            ```python
            git rm --cached elarchivo
            ```

        - repetir el proceso de git add, commit y push
    - Tienes una carpeta de your-code que es la que pusimos nosotros en el repo 👀 borra todo aquello que no añada valor.
    - Dentro de la carpeta `src`  procura que sean sólo archivos de código. Ni jupyters ni imágenes. Las imágenes las puedes dejar en una carpeta de imgs o una de output, como veas, pero separadas de src.
    - El ejecutable suele estar fuera, a nivel de root. Es el archivo que suele llamarse `[main.py](http://main.py)` y es el que se buca cuando te descargas una aplicación/programa/repo.

- El **[README.md](http://readme.md) ✍🏻**: está genial. Conciso, explicando lo que has hecho y lo que has utilizado. También has puesto un ejemplo de lo que consigues. Como tienes un ejecutable, puedes añadir:
    - requirements.txt (utiliza la librería pipreqs)
    - instrucciones a la persona que se lo clone: clónalo, ejecuta este archivo,  esto es lo que puedes esperar

- El ejecutable ⚡️:  está súuuper top 🔥 lo único es lo que te decía, que el código tiene que estar **modularizado**.
- Respecto al código 👩‍💻:
    - En el **src**:
        - Súper bien los docstrings
        - Y las comprehensions lists y el zip!
        - Esta función:

            ```python
            plt.plot(df_curry['year'], df_curry['pts'], linestyle = 'solid', marker = '.', color = 'blue')
            plt.plot(df_westbrook['year'], df_westbrook['pts'], linestyle = 'solid', marker = ".", color = 'green')
            plt.plot(df_paul['year'], df_paul['pts'], linestyle = 'solid', marker = ".", color = 'red') 
            plt.plot(df_harden['year'], df_harden['pts'], linestyle = 'solid', marker = ".", color = 'orange')
            plt.plot(df_durant['year'], df_durant['pts'], linestyle = 'solid', marker = ".", color = 'purple')
            plt.plot(df_wall['year'], df_wall['pts'], linestyle = 'solid', marker = ".", color = 'brown') 
            plt.plot(df_james['year'], df_james['pts'], linestyle = 'solid', marker = ".", color = 'pink')
            plt.plot(df_lowry['year'], df_lowry['pts'], linestyle = 'solid', marker = ".", color = 'gray')
            plt.plot(df_griffin['year'], df_griffin['pts'], linestyle = 'solid', marker = ".", color = 'olive')
            plt.plot(df_harris['year'], df_harris['pts'], linestyle = 'solid', marker = ".", color = 'cyan')
            ```

            la puedes refactorizar; quizá con un diccionario.

    - En los **jupyters**:
        - El story telling está súper bien.
        - En el primer jupyter, limita el output 🙏 que es muy difícil encontrar el código
        - Para crear las nuevas columnas en los dfs, igual puedes refactorizar también guardándolo en diccionarios/listas y poniendo un bucle.
        - El código que tengas modularizado en los archivos de python, quítalo del jupyter, para que no sea redundante.

En resumen: tienes el ejecutable, has enriquecido los datos y has hecho un buen story telling. Te dejo estas cosas para modificar/que tengas en cuenta, pero está genial el proyecto Unai.

Enhorabuena! ahora, a por las geoqueries! 💪
