### ISSUE TITLE
[W3-pipelines-project] Alejandro Sánchez

### ISSUE THREAD

**Issue by as-Solo** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#3]
https://github.com/as-Solo/Estrella_Michelin_2019

**Comment by breogann** [comment]
Hola Alejandro! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

  - Dataset original: estrellas michelín (kaggle)
  - Enriquecido con: web scrapping IMDB
  - Has relacionado los datos con: rating

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: genial, no se te ha colado ningún archivo temporal y has añadido lo que no te hacía falta. El csv de Kaggle no hace falta que lo ignores (a menos que te lo pidan), el de Sharks creo que era una excepción.
    - Por lo demás, la organización está clara: tienes una carpeta de src y tienes los jupyters numerados y organizados en un carpeta de notebooks; así está perfect.

- El **[README.md](http://readme.md) ✍🏻**:
    - No se te renderiza la imagen. Este es el código que tienes puesto:

        ```python
        ![portada_Michelin.jpg](attachment:portada_Michelin.jpg)
        ```

    - En general, cuando defináis el objetivo del proyecto no lo hagáis desde la parte personal/educativa, sino desde la parte de "lo que quieres conseguir haciendo todo esto". Es decir, no enfoques el objetivo a "esto lo hago para aprender o el objetivo es ampliar un csv". El objetivo es responder a una pregunta (sin necesidad de plantear una hipótesis formalmente) y enriquecer es el medio. El aprendizaje es un beneficio secundario (de cara a tu portfolio, no de cara a ser estudiante), ifyouknowwhatimean.
    - El resto del readme está genial: has explicado lo que has hecho, el origen de lo datos
    - Sólo: ¿de dónde has escrapeado? ponlo también en el readme
    - Has puesto BeautifulSoap en vez de Soup 🙃, pero genial por incluir los enlaces 👏
- El ejecutable ⚡️: ya tienes archivos de scrapping, es cuestión de simplemente importar el df y llamar a las funciones.
- Respecto al código 👩‍💻:
    - En el **src**:
        - Siempre que hagas control de flujo con if/elif/else, pon un if y un else. El resto deberían ser elif. ¿Por qué? porque python va a entrar a valorar todos los ifs, independientemente de si se cumple o no la condición anterior. Es decir, que varios if's juntos es para valorar condiciones que se pueden dar a la vez; no son excluyentes. En cambio si python lee varios ifs cuando las condiciones sí son excluyentes, implica mayor tiempo de procesamiento.

            ```python
            def media_precios(datos):
                '''
                Get one or two values and makes the mean
                Args:
                    object Dataframe value
                Retuns:
                    float
                '''
                
                if datos == 0:
                    return 0
                
                if len(datos) == 1:
                    return datos[0]
                
                if len(datos) == 2:
                    return round( (datos[0] + datos[1]) / len(datos) ,2)
            ```

        - Aquí:

            ```python
            def scrap_precio(web_michelin):
                web =  web_michelin
                html = requests.get(web)
            ```

            parametrizas con web_michelin y luego creas una variable para guardar ese parámetro que luego llamas en otro sitio. Pon el parámetro como web y eso que te ahorras, ¿no? 👀

            ```python
            def scrap_precio(web):
                html = requests.get(web)
            ```

        - Lo mismo con esto:

            ```python
            texto = cadena
            precios = re.findall(patron_precio, texto)
            ```

            re-asignar variables acaba siendo redundante y puede llevar a confusión (sobre todo a ti y a Python).

        - Los docstrings están súuuper bien
        - BUENO, te has lanzado con regex 🤩
        - Los return están súper bien puestos también. Me refiero a esto:

            ```python
            if len(horario) == 0:
                return 'Sin información'

            return horario.getText().strip('\n')
            ```

            porque así te ahorras condiciones lógicas.

        - El código que tienes está muy bien; simplemente te digo detalles que creo que lo pueden mejorar, pero no está nada mal.
    - En los **jupyters**:
        - **03_visualizacion_de_datos.ipynb:** no se renderizan los mapas y no al clonármelo no puedo cargar el df porque está ignorado 🥲
        - **04_Conclusiones.ipynb:** está genial. Conciso, claro y enseñenado lo que tienes que enseñar en el story-telling.

En resumen: te falta el ejecutable, pero tal y como tienes el código es súper fácil de conseguir (cuestión de llamar lo que ya tienes definido). Has enriquecido un dataset haciendo scrapping y tienes una buena organización del proyecto. Tu código, por lo general, está bastante bien: está "recogido" y es el necesario para hacer lo que tienes que hacer. 

Sólo te queda hacer el ejecutable, pero has hecho el pipeline con un dataset que has enriquecido a través de scrapping, y la visualización no la puedo ver pero tiene súuper buena pinta. 

Estoy seguro que este proyecto de geoqueries lo vas a petar 💪
