### ISSUE TITLE
[W3-pipelines-project] Emilio C.

### ISSUE THREAD

**Issue by emilio-carrasco** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#4]
https://github.com/emiliocarrascomoreno/criptwit

**Comment by breogann** [comment]
Hola Emilio! 🙋🏻‍♂️

Como siempre digo: damos todo el feedback posible, pero eso no quiere decir que esté mal. 

El proyecto tenía dos objetivos: **enriquecer** datos & hacer un **pipeline**. 

- Para el primero: utilizar una API o web scrapping para relacionar los datos.
- Para el segundo: que  haya un pipeline quiere decir que el resultado de una función fuera la entrada de otra. Es decir, que ejecutando una acción, los datos se procesen de varias formas para devolver un output diferente al inicial. Aquí puedes hacer un ejecutable donde el resultado de la primera función (la descarga del dataset) sea la entrada de la(s) segunda(s) funcion(es) de limpieza. El flujo de ejecución sería:

    ruta  > df_descargado > df_limpio

**Has utilizado:**

- Dataset original: Kaggle
- Enriquecido con: API coingecko

- El **[README.md](http://readme.md) ✍🏻**:
    - Explicas el objetivo, el proceso, citas las fuentes y qué pasa en cada momento 👌
    - Échale un ojo al teto, que tienes algunas erratas

- Respecto a la **organización del repositorio 📚**
    - El .gitignore: no se te ha colado ningún archivo temporal ni variables de entorno.
    - El `main.py` (ej este caso el criptwit.py) está perfecto en la root.
    - Lo que tienes en libs es lo que tendría que ir en la carpeta de src. Lo que tienes en src, ¿te aporta valor?
    - Genial el requirements.txt. Me ha clonado tu repo, creado un ambiente e instalado los requirements. Me ha funcionado todo. Puedes incluir instrucciones en el readme para crear entorno.

- El ejecutable ⚡️: el pipeline está perfecto. Si quisieras, podrías añadir algo tipo:

    ```python
    os.system("open data/archivo.png")
    ```

    para que se te abra una gráfica tras ejecutar todo. También, te dejo este artículo para el ejecutable: [https://medium.com/python-features/understanding-if-name-main-in-python-a37a3d4ab0c3](https://medium.com/python-features/understanding-if-name-main-in-python-a37a3d4ab0c3)

- Respecto al código 👩‍💻:
    - Está genial incluir los docstrings, pero ten cuidado, ponlo o todo en castellano o todo en inglés.
    - El código está súper bien Emilio, la verdad que no tengo nada que decirte.
    - Lo único que quizá echo en falta es la parte del story-telling. Pudes hacer un jupyter sencillo explicando lo que has encontrado y acompañándolo de las gráficas.

Has entendido el concepto de pipeline, el de ejecutable y has enriquecido los datos haciendo un buen estudio. Enhorabuena porque está muy bien el proyecto!
