### ISSUE TITLE
[W3-pipelines-project] Julieta Staryfurman

### ISSUE THREAD

**Issue by julistary** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#5]
https://github.com/julistary/pipelines_project.git

**Comment by AnaAGG** [comment]
# 🎬🎬 Proyecto Pipelines 🎬🎬

Hola hola Julieta 🙋‍♀️, vamos con la corrección del proyecto de pipelines!

## Readme
El readme esta perfecto Julieta, es claro y conciso explicas lo que haces de forma esquemática y muy organizada, buen trabajo! Por ponerme un poco finolis te dejo por aquí un par de comentarios por si te aportan valor para el futuro:

- Te has descargado un dataset de kaggle, estaría muy guay que pusieras en el `readme` el link que te lleva a la página donde descargartelo.

- Explicas cual es el objetivo del proyecto a nivel técnico, me falta un poco la motivación de por qué IMDB y qué es lo que buscabas en tu datos. 

## Estructura del repositorio

- Perfecto! No se te ha escapado ningún archivo temporal ni el token 🎉

- Tienes un archivo que se llama `functions.py`, para el futuro... intenta no usar estos nombres tan generales, un archivo nunca puede llamarse functions 😉. Dale siempre un nombre más descriptivo, que antes de entrar al archivo ya sepa de que va a ir un poco. 

- Como has descargado los datos de kaggle recuerda que desde kaggle nos piden que no pongamos públicamente el dataset en nuestros repos. Para La próxima puedes meterlo en el `.gitignore` o no subirlos. 

- 🔝 Todas las funciones con sus doctrings!


## Sintaxis de código

Tu código esta suuper bien, te dejo por aquí unos detalles por si te aportan valor: 
 - Vamos con la función `calling_api` esta perfecta pero te dejo por aquí una idea.

    - Y si en vez de guardarlo primero en una lista y luego convertirlo a diccionario, lo almacenas directamente en un diccionario?
- Recuerda, los nombres de las variables en minúscula!
- Recuerda, los *import* siempre fuera de las funciones. Tienes un *import* dentro de la función `resul_to_df`. Lo pusiste dentro por que te dio problemas? Si es así tenemos que mirar eso!
- En al función `enrichment` tienes una parte de la función donde tienes código que se repite. En tu caso son 4 veces, una por cada actor. Cuando pasa eso tenemos que intentar atomizar el código. En este caso, los diccionarios pueden funcionar muy bien, donde las `keys` serán tus columnas y los values los valores de la columnas.
    - En esta parte del código de esta función:
        ```python
        for g in genres_list: #iteras por una lista
            g = set(g) # g será solo un elemento, entonces... que sentido tiene hacer un set ❓
            if len(list(g.intersection(main_categories))) > 0:
                genres_clean.append(list(g.intersection(main_categories)))
            else:
                genres_clean.append(list(g))
        ```

- Por ponerme tiquismisquis, en python cuando te creas una lista vacía nueva por convenio se hace poniendo `[]` 
    ```python
    #como lo haces
    genres_list = list()

    # como podrías hacerlo
    genres_list = []
    ```
Vamos con la parte de visualización:

- La columna `Unnamed: 0` es la columna del índice y se te crea cuando haces la exportación del dataframe a csv. Hay dos formas en las que puedes evitar tener que quitarla: 
    - Cuando estas exportando el *dataframe* :
        ```python
        df.to_csv('file.csv', index=False)
        ```
    - Cuando cargas el csv:
        ```python
        pd.read_csv('file.csv', index_col=[0])
        ```
- EL resto de la visualización esta perfecta!!

## ToDo

- Atomizar algunas partes del código

- En la visualización te animo a que te lances con las funciones. Al final, tienes líneas de código que son bastante similares, solo que se plotean datos diferentes. Si haces una función para cada tipo de gráfico 

Bueno Julieta muy buen trabajo en este proyecto (as usual 😉). Menudo rollazo te puse! Pero el proyecto esta perfecto! En este proyecto te has descargado un dataset, lo has enriquecido con dos fuentes de datos diferentes (web scrapping y llamadas a API) y luego has extraído conclusiones con todos los datos a través de la visualización. Enhorabuena por tu trabajo 🚀🚀💪💪

![image](https://user-images.githubusercontent.com/75084991/115108167-3687fc80-9f6f-11eb-9af7-9f1c33acddf2.png)
