### ISSUE TITLE
[W3-pipelines-project] Alberto Pérez-Lescure

### ISSUE THREAD

**Issue by Albertoplm** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#6]
[Link here](https://github.com/Albertoplm/Pipelines-project.git)
https://github.com/Albertoplm/Pipelines-project.git

**Comment by AnaAGG** [comment]
# 💲 Proyecto Pipelines Lescure 💲

Hola hola Alberto 🙋‍♀️, aquí estoy de nuevo con la corrección del proyecto de pipelines!

## Readme
El readme está perfecto Alberto, muy bien descrito todo el trabajo que has hecho en el proyecto, claro y conciso. Solo como detalle para el futuro: 
- En las gráficas se ven un poco regulinchi los ejes. Al estar en negro con el fondo negro cuesta leerlo. Pero es solo un detalle. 

## Estructura del repositorio

La organización del repo esta perfecta, no se te ha pasado ningún archivo raro en ningún sitio, en la carpeta `data` no has metido la base de datos de kaggle. Por ponerme fina:
- Cuando tienes varios jupyters esta bien que los numeres para saber cual es el orden que siguen. Sé que lo tienes en el readme, pero cuanto más intuitivo mejor!

- Los docstrings los tienes en algunas funciones y en otras no. Lo ideal es que estén en todas

- Las importaciones de librerías siempre al inicio del jupyter

## Sintaxis de código

- No crees funciones dentro de funciones. Es mejor que las definas por separado y que luego llames a las funciones dentro de otra que lo haga todo. 

- En la función `crypto_scrapping` esta bien como sacas los valores de las filas y las columnas. Te creas un diccionario que luego pasas a lista. Este paso lo puedes omitir. Puedes convertir el diccionario que generas del *scrapping* en un dataframe directamente. 
    - Por otro lado, en esta función lo que haces es haces 7 scrapeos idénticos pero a distintas páginas diferentes. Atomiza este código, tienes el mismo código repetido 7 veces cambiando solo la url. Podrías pasar la url como un parámetro en tu función evitando tener que repetir código. ‼ Recuerda, siempre que veas que en tu código hay una estructura que se repite mucho... a atomizar ‼

- Cuando conviertes el mes de letras a numérico, muy bien usada la libreria `datetime`. Este es un buen ejemplo de código bien atomizado. Pero... 
Estas dos cosas hacen lo mismo. Porque las tienes las dos??? 🤷‍♀️🤷‍♀️

    ```python
        
    crypto_table["date"] = [str(fecha.replace('ene.', '-01-')) for fecha in crypto_table["date"]] 
    crypto_table["date"] = [str(fecha.replace('feb.', '-02-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('mar.', '-03-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('abr.', '-04-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('may.', '-05-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('jun.', '-06-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('jul.', '-07-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('ago.', '-08-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('sept.', '-09-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('oct.', '-10-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('nov.', '-11-')) for fecha in crypto_table["date"]]
    crypto_table["date"] = [str(fecha.replace('dic.', '-12-')) for fecha in crypto_table["date"]]
        
        
    def date_convert(date_to_convert):
        return datetime.datetime.strptime(date_to_convert, '%d -%m- %Y').strftime('%Y-%m-%d')

    crypto_table.date = crypto_table.date.apply(date_convert)
    ```
- En la visualización. Cuando creas las funciones para convertir a `int` o `float`, suuuper bien creadas las funciones. Como detalle, en vez de hacer el apply para cada una de las columnas independientemente, puedes hacerlo para varias columnas a la vez. Te dejo por aquí como sería por si te aporta valor
    ```python
    df[["open 1", "max_v"]] = df[["open 1", "max_v"]].apply(string_to_int)
    ```
    - ⚠️ Aquí igual, tienes dos funciones que haces casi lo mismo, `string_to_int` y `string_to_int2`. Las usas las dos, pero en realidad entiendo que solo te interesa una... Intenta simplificar esto. 

- Vamos con la última parte de la visualización. Las gráficas estas super bien, se entienden perfectas. Sobre el código que hay detrás de ellas. De nuevo, si te fijas repites 7 veces el mismo código para cada una de las figuras que haces. Te podrías crear una función para cada tipo de gráfica que luego apliques a cada dataset de los que te creas. 


## ToDo

- Como te decía arriba, intenta unificar y poner los dosctrings en todas las funciones. 

- Atomizar el código en algunos puntos, *web scrapping* y visualización principalmente. 

- Un poco de explicación sobre los conceptos básicos para la interpretación de las gráficas. 

- Una explicación un poco más detallada sobre lo que representa cada gráfica en el jupyter de visualización.

Bueno Alberto, buen parrafazo te escribí, pero... don`t panic!! El proyecto esta muy bien 🔝🔝. Has aprendido a hacer un ejecutable, a enriquecer tu base de datos y sobre todo te has animado con el *web scrapping*. Revisa las cositas que te comento y si te queda alguna duda ya sabes donde estamos 😉


![image](https://user-images.githubusercontent.com/75084991/114815993-9d62b580-9db7-11eb-8484-804950802a4c.png)
