### ISSUE TITLE
[Pipelines-Project-w3] Javier Cabrera

### ISSUE THREAD

**Issue by Javi-Python** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#7]
https://github.com/javielpapi/Pipeline-Project-w3

**Comment by AnaAGG** [comment]
# 💲💲 Proyecto Pipelines 💲💲

Hola hola Javi 🙋‍♀️, vamos con la corrección del proyecto de pipelines!

## Readme

En general el readme esta suuuper bien Javi! Está todo claro, con todo muy bien explicado. Se puede seguir el *workflow* de tu proyecto fácilmente. 

- Me gustó muchísimo que hicieras un apartado para explicar que haces en cada uno de los jupyter, esto hace que sea mucho más fácil de seguir 🔝

- Solo por ponerme un poco finolis, cuando indicas todas las librerías que has usado en el proyecto, sería perfecto que pusieras los links a la documentación oficial. Además, no ha hace falta que pongas `import pandas`, con que pongas `pandas` esta perfecto! 

- Como te has descargado parte de los datos de kaggle y no deberían estar en el repo, lo ideal es que pusieras un link a la página de kaggle donde la gente puede descargar los datos. 

- Te han faltado algunos *docstrings* en algunas funciones. Dale duro ahí en los próximos proyectos 💪

## Estructura del repositorio

- Sobre el `.gitignore` se te ha pasado algún archivo temporal como el `DS_Store`. ⚠ ‼ Ojo Javi!! Volviste a dejarte el token de la API de rapidapi en el repo (está en el `.py` de functions) ‼ ⚠

- ¿`Functions.py`? Lo ideal es que no lo llames así, que le des un nombre algo más descriptivo. Si esa `.py` es para la limpieza de datos de la API llamalo `cleaning_API.py`

- Tienes archivos vacíos en tu repo, como `my-proyect.py`. Intenta no dejar este tipo de archivos va? 

- Por ponerme un poco finolis, tienes por duplicado los ficheros de datos que has usado en el repo. Unos en la carpeta `database` y otros en la carpeta `data`

## Sintaxis de código

Vamos con el primer jupyter (`Clean Up and Enrichment (V_final)`)

- Empiezas cargando los datos con `pd.read_csv` y luego usas `pd.DataFrame` para convertir tu csv en un dataframe. Date cuenta que con las primeras líneas de código (usando `pd.read_csv`) ya tienes tu csv en un dataframe, no te haría falta la segunda parte. 

- Cuando mergeas las dos tablas de bitcoin y etherum usas el `merge`, no esta mal. Pero en tu caso creo que hubiera ido mejor el método `concat` ya que las dos tienen la misma estructura de columnas, lo que harás será añadir las filas de una dataframe debajo de las filas del otro. Así, evitaras los NaN
    ```python
    bit_eth2 = pd.concat([ether, bitcoin], axis=0)
    ```
- En la función para extraer los valores para cada "stock" a través de la API. Tienes una función (`responsedf`) que iba suuper bien encaminada y que te hubiera evitado mucho trabajo posterior. Te dejo por aquí que es lo que te faltaba en al función:
    ```python
    def responsedf(response, stocks):
        diccionario = {}
        x = response.get(stocks)
        print(x.keys())
        for k, v in x.items():
            if k == 'timestamp' or k == 'dataGranularity' : # aquí puedes meter todos los parámetros que quieras de cierto stock
                diccionario[k] = v
        return diccionario

    MSFT = responsedf(response, 'MSFT')   
    MSFT = pd.DataFrame(MSFT)
    ```
- El resto de las funciones suuper bien definidas, cortitas y con objetivos claros 👏

- En la parte de visualización has hecho un gran trabajo. Muchas gráficas, relacionando todos los datos que has obtenido! Te dejo por aquí algunos detalles por si te aportan valor en el futuro:
    - Tienes líneas de código que repites en varias gráficas, como el los plots de barras. ¿Qué podrías hacer? Crearte una función para este tipo de gráfico. Lo mismo para los *scatterplots*
## ToDo

En general Javi, muy buen trabajo en este proyecto. Enhorabuena por todos los datos que has usado, se nota que te has peleado y currado este proyecto. 

- Me falta un poco de explicación de cada gráfica, que nos están contando, que significa lo que yo veo en cada gráfica? 

- Dale a la atomización de código, sobre todo en la visualización! 

![image](https://user-images.githubusercontent.com/75084991/115216521-dd51d180-a104-11eb-9d5b-49c2501b1aeb.png)
