### ISSUE TITLE
[W3-pipelines-project] Susana Martin

### ISSUE THREAD

**Issue by Sussi-MW** [Ironhack-Data-Madrid-Marzo-2021/W3-pipelines-project#8]
https://github.com/Sussi-MW/pipelines-project.git

**Comment by AnaAGG** [comment]
# 🎬🎬Proyecto Pipelines 🎬🎬

Hola hola Susana! Vamos con las correcciones del proyecto de las Pipelines 

## Readme

Sobre el readme tengo poco que decirte, en general esta muy bien. Esquemático, donde describes super bien el contenido de ficheros del repo y el objetivo de cada uno de ellos.  Me han faltado un par de cosillas, te las dejo por aquí:

- Una pequeña descripción del dataset de kaggle, que información nos da y sobre qué. Lo mismo para la API. 

- Siempre está bien añadir las librerías que has usado en el proyecto. Si a la lista de las librerías le añades el link a la documentación oficial sería 🔝

## Estructura del repositorio

Que susto me di cuando no vi el jupyter de visualización! Esta en el output. Estaría guay que los jupyter lso metas en una carpeta diferente o por lo menos que no los metas en el Output

- 🔝 Todas las funciones con sus docstrings, muy bien documentadas.

## Sintaxis de código

- Al final del archivo `.py` tienes usas el estamento `__name__`. Entiendes lo que hace esta parte del código?
    ```python
    def main():
        pass
    # Press the green button in the gutter to run the script.
    if __name__ == "__main__":
        main()
    ```
    Basicamente lo que hace es: 

    ```python
    if __name__ == "__main__":
    # Do something here
    ```
    Tu tienes des pues de esta estamento una función que no hace nada, tiene un `pass`, por lo tanto no ocurrirá nada cuando ejecutes tu .py. 👀 Te dejo algo de [docu](https://medium.com/python-features/understanding-if-name-main-in-python-a37a3d4ab0c3) sobre este tema

- En la función `get_original_language` en el return tienes un `-`. Esto no suele ser habitual. En este caso que lo que haces en esa función es llamar a la API, lo que puedes hacer es que el return sean los resultados de la llamada a la API. 

## ToDo

- En la parte de visualización me falta un poco de *story telling* y sobre todo que añadas una parte de interpretación de los resultados ¿Qué nos están contando las gráficas?

- Me ha faltado el ejecutable que cuando lo corra en la terminal me haga todo de un tirón. 

- Has sacado este ejercicio con muy poquitas funciones, te podrías haber metido un poco más en los dataframes para sacar más cositas, tu puedes Susana!! Al final, los proyectos son un poco para "enfangarnos" en todas las herramientas que hemos ido viendo durante el curso. 

Bueno Susana, en este proyecto te has descargado un dataset, lo has enriquecido con más datos de una API y has combinado todos los resultados en la parte de visualización. Vamos Susana, segundo proyecto superado!!!!


![image](https://user-images.githubusercontent.com/75084991/115157443-907ce500-a089-11eb-82e4-15257f041957.png)
